version: '3'

services:
  app:
    build: 
      context: ./node
    image: wagnerreissilva/node
    container_name: app
    volumes:
      - ./node:/usr/src/app
    tty: true
    networks:
      - mynetwork
    ports:
      - "3000:3000"

  nginx:
    build: 
      context: ./nginx
    restart: always
    image: wagnerreissilva/nginx
    container_name: nginx
    networks:
      - mynetwork
    ports:
      - "8080:80"

  db:
    image: mysql:5.7
    container_name: db
    restart: always
    tty: true
    volumes: 
      - ./mysql:/var/lib/mysql
    environment: 
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - mynetwork

networks:
  mynetwork:
    driver: bridge